apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: k8s-admin-informer
  name: k8s-admin-informer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    release: k8s-admin-informer
